### ISSUE TITLE
User Story 1: As a user of the VolumeGauge, I want tracking for each contract that I use on the AMM

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#1]
As a user of the VolumeGauge, I want the gauge to track my AMM trades for each contract or pool that I interface with on the AMM so that my trades for each contract can be tracked.

NOTE: There is no need for deposit or withdrawals with this gauge as this contract is simply to track the appropriate volume and the sources.

**Comment by michwill** [comment]
I'd say that 1 gauge is for 1 pool contract. For simplicity

**Comment by taariq** [comment]
The list of contracts are available here: https://www.curve.fi/contracts

**Comment by taariq** [comment]
question: @michwill do we want upgradeability on these contracts?

**Comment by taariq** [comment]
"We don't use any upgradeability pattern. If you want a new version, you replace the entire gauge. " Thanks @michwill

**Comment by taariq** [comment]
@webelf101 Please consider using interface instead of raw_call. Please reply here with any limitations you identified in interface.

**Comment by taariq** [comment]
Closing as submitted.
