### ISSUE TITLE
User Enhancement: Update the V-EMA reads from daily to hourly

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#14]
Feedback was that instead of reading the data once per day, we read it once per hour.

Let's update our VolumeGauge for once per hour.

**Comment by webelf101** [comment]
Just now, I already set once per 10 minutes instead of a day. Do you prefer per 1 hour?

**Comment by taariq** [comment]
Where's the line where we read once per 10 minutes?

**Comment by webelf101** [comment]
https://github.com/Promise-Protocol/volumegauge/blob/d8c564a6a8b7dc8604c2759375d7a8a341a9a2fc/contracts/volumegaugetracker.vy#L32
I set this value as 600 and deployed it as a test.
Currently, Brownie test doesn't deploy but only uses the contract I deployed.

**Comment by taariq** [comment]
@webelf101 closing as agreed that we'll go for 600 as default.
