### ISSUE TITLE
User Story 3: As a user, I want the VolumeGauge to store the following information

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#3]
will store the information about the volume traded from my source addresses to the exchange and AMM contract addresses so that my record of my trade volume is available for rewards.

* Number of tokens traded
* Price of the tokens traded
* What addresses trade
* Timestamp for each trade

**Comment by webelf101** [comment]
What exactly is "Volume traded"?

**Comment by taariq** [comment]
> What exactly is "Volume traded"?

Good question. We want to know the Price AND Number of tokens that were traded. I will update the story.

**Comment by taariq** [comment]
Closing as submitted.
