### ISSUE TITLE
User Story 4: As the deployer of the VolumeGauge, I want gas costs to be optimized

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#4]
As a deplyer of the VolumeGauge, I want the gas consumed by the gauge to be lowest possible so that we can cover the cost of the VolumeGauge gas usage.

**Comment by porkchop** [comment]
1. Does this apply to every gauge function? Like this is basically write *efficient code* yeah?
2. Are we intending to cover gas costs? I was expecting users to be responsible for their own gas

**Comment by taariq** [comment]
Users cover gas, but we want to be gas optimized.

**Comment by taariq** [comment]
Closing as submitted.
