### ISSUE TITLE
User Story 5: As a user, I want the VolumeGauge to use a moving average function to smoothen trading rewards

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#5]
As a user, I want the VolumeGauge to implement an exponential smoothing function or some easier smoothing function such as a linear smoothing function of calculating the daily rewards for users based on their trading so that as a user I get a smooth distribution of rewards for trading.

**Comment by porkchop** [comment]
Isn't the purpose of this to decay the user's rewards so as to make sure they maintain a level of trading activity?

**Comment by taariq** [comment]
Yes. The purpose of the linear smoothing function is to smooth rewards as trades continue. The goal is to ensure they maintain a level rate of trading activity. We did work on this in promise and I think we can try for a Linear Weighted Moving Average (LWMA) which can be seen here: https://www.investopedia.com/terms/l/linearlyweightedmovingaverage.asp. This smoothens the rewards, but is still responsive for traders that move volume recently. We can try this and see how others may turn out, but the link should provide an easy way to calculate.

**Comment by taariq** [comment]
Here's another example: A dynamic swap fee algorithm that we may explore to apply to a VolumeGauge trader rewards.

- based on volatility : higher volatility, higher rebates
- reward = 0.01 % + 0.4% * volatility
  - if volatility = 0%, then reward = 0.01%
  - if volatility = 60%, then reward = 0.025%
  - if volatility = 150%, then reward = 0.07%
  - volatility can be calculated from min/max price in a period
![image](https://user-images.githubusercontent.com/38277329/100219052-df9a7000-2f58-11eb-8ae0-6582f3946073.png)
(https://www.eurexchange.com/resource/blob/43140/47ca53f0178cec31caeecdf94cc18f6e/data/volatility_and_its_measurements.pdf.pdf)
  - n = 30days, H,L for each 24 hours (1day high/low)

this algorithm automatically allocate 0.01% rebate for stable pairs, higher fee for higher volatility pairs

_Originally posted in https://github.com/tendermint/liquidity/issues/43#issuecomment-733635470_

**Comment by webelf101** [comment]
What is the result of this feature?

**Comment by taariq** [comment]
> What is the result of this feature?

As a result of this feature, as a user, I will get a reward for my trades that is 0.02% of the trade volume * by the 7 day moving average of my trade so that my rewards are smooth for each day.

Currently Curve charges 0.04% of the trade and rewards holders of VeCRV with 50% of the trade fee. We are calculating the reward fee based on this smoothing function. Does that clarify?

**Comment by taariq** [comment]
Closing as delivered and upgrading to a new story
