### ISSUE TITLE
User Story 6: As a user, I want the VolumeGauge to track all my trades on all contracts in one contract

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#7]
As a user, I want the VolumeGauge to track all my trades on all contracts in one contract so that the system will store all contract trades onchain in one contract.

1. Requirements:
Successful trade tracking in one contract.

**Comment by taariq** [comment]
@webelf101 We need to still do this one. Yes?

**Comment by webelf101** [comment]
Yes, we need to keep this ticket.

**Comment by webelf101** [comment]
This story is not an individual ticket. This is basically done and we need to update whenever we add volumegauge to every pool.

**Comment by taariq** [comment]
Okay. Closing as done.
