### ISSUE TITLE
OPTIMIZATION: Limit reads from storage which may consume gas in swap_volumegage.vy

### ISSUE THREAD

**Issue by taariq** [Promise-Protocol/volumegauge#8]
When you use self.base twice, it reads it from storage twice which is not optimal.
better to:
```
_base: address = self.base
...
SWAP(_base)...
...
something-something _base
...
```

**Comment by taariq** [comment]
@webelf101 did you review this ticket?

**Comment by webelf101** [comment]
Yes, I reviewed and keep read/write limitation.

**Comment by taariq** [comment]
Okay. We will close as delivered.
